version: 2
updates:
  - package-ecosystem: npm
    directory: /backend
    open-pull-requests-limit: 0
    schedule:
      interval: weekly
    groups:
      security:
        applies-to: security-updates
        patterns: ["*"]
  - package-ecosystem: npm
    directory: /web
    open-pull-requests-limit: 0
    schedule:
      interval: weekly
    groups:
      security:
        applies-to: security-updates
        patterns: ["*"]
  - package-ecosystem: npm
    directory: /integrations
    open-pull-requests-limit: 0
    schedule:
      interval: weekly
    groups:
      security:
        applies-to: security-updates
        patterns: ["*"]
  - package-ecosystem: npm
    directory: /worker
    open-pull-requests-limit: 0
    schedule:
      interval: weekly
    groups:
      security:
        applies-to: security-updates
        patterns: ["*"]
  - package-ecosystem: npm
    directory: /acceptance
    open-pull-requests-limit: 0
    schedule:
      interval: weekly
    groups:
      security:
        applies-to: security-updates
        patterns: ["*"]
  - package-ecosystem: github-actions
    directory: /
    open-pull-requests-limit: 0
    schedule:
      interval: weekly
    groups:
      security:
        applies-to: security-updates
        patterns: ["*"]
